version: "3.8"

services:  
  angular:
    container_name: angular
    restart: always  
    build: 
      context: ./frontend
    ports:
      - "${FE_PORT}:80"
    expose:
      - 80   

  postgres:
    container_name: postgres
    image: postgres:14-alpine 
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_storage:
    driver: local