version: "3.8"


services:  
  angular:
    container_name: angular
    restart: always  
    build: 
      context: ./frontend
    ports:
      - "80:80"
    expose:
      - 80   

# ДОРАБАТВАЕМ
  # agent:
  #   container_name: agent
  #   build:
  #     dockerfile: Dockerfile    
  #   image: agent
  #   env_file:
  #     - ".env"
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:1234@db:5555/medfusion

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage  

  postgres:
    container_name: postgres
    image: postgres:14-alpine 
    restart: unless-stopped
    
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT} 
    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  qdrant_storage:
    driver: local
  postgres_storage:
    driver: local