version: "3.8"

## weaviate -- будет лучше в контексте retriever

services:
  
  # angular:
  #   container_name: angular
  #   restart: always  
  #   build: 
  #     context: ./frontend
  #   ports:
  #     - "80:80"
  #   expose:
  #     - 80   

  # fastapi:
  #   container_name: fastapi  
  #   restart: always  
  #   build: 
  #     context: .
  #   ports:
  #     - "1212:8000"
  #   command: poetry run gunicorn backend/main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
  #   depends_on:
  #     redis: 
  #       condition: service_started

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.10.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage  

volumes:
  qdrant_storage:
    driver: local